title: Friday A.I
description: This project is inspired by Marvel's Iron Man/Tony Stark who created Friday A.I. after his first virtual assistant Jarvis got destroyed.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
